name: Deploy Wazuh Rules
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: add gpg
        run: curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && chmod 644 /usr/share/keyrings/wazuh.gpg
      - name: repo add
        run: echo "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main" | tee -a /etc/apt/sources.list.d/wazuh.list
      - name: update repo
        run: apt-get update
      - name: Install Wazuh Agent
        run: sudo apt-get install -y wazuh-agent
      - name: Deploy Rules
        run: cp ./rules/*.yaml /var/ossec/etc/rules/
      - name: Restart Wazuh
        run: sudo systemctl restart wazuh-manager